language: python
sudo: false
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

env:
    matrix:
        - RUN_ITERATION=1

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytest numpy pip coverage toolz pandas scikit-learn cytoolz dill networkx pyzmq ipython bcolz chest blosc cython
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then conda install bokeh; fi
  - pip install git+https://github.com/mrocklin/partd --upgrade
  - pip install blosc --upgrade
  - pip install git+https://github.com/Blosc/castra

  # Install dask
  - python setup.py install

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run $(which py.test) dask --runslow --doctest-modules --verbose; else py.test dask --verbose; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage report --show-missing; pip install coveralls ; coveralls ; fi

notifications:
  email: false
